### PR TITLE
Made ogimage dynamic

### PR DESCRIPTION
**Pull request by EncryptEx**
By replacing a local path to the website's ogimage will make easier the process of changing banners from repo to repo (only one will be needed)

### CODE REVIEW

**Review by mauriciabad — APPROVED** [review]
Well, the ogimages should be different if we want to offer the best experience. But it's good enough to reuse it.

I checked, and there's no issue if the ogimage has a different domain. [Source](https://stackoverflow.com/q/47463243)

**Comment by mauriciabad** [comment]
Don't forget to remove the old ogimage

**Review by mauriciabad — CHANGES_REQUESTED** [review]
Don't forget to remove the old ogimage.

And also update the actual ogimage tag in the index.html

**Comment by EncryptEx** [comment]
Done!

**Review by mauriciabad — APPROVED** [review]

**Pull request merged**
